apiVersion: v2
name: monitoring
description: A Helm chart for monitoring stack (Prometheus, Grafana, Node Exporter)
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - monitoring
  - prometheus
  - grafana
  - kubernetes
dependencies:
  - name: prometheus
    version: 25.8.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: kube-state-metrics
    version: 5.21.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-state-metrics.enabled
  - name: prometheus-node-exporter
    version: 4.48.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-node-exporter.enabled
