# Monitoring Stack Configuration
# 監控系統配置

# Global settings
global:
  namespace: monitoring

# Prometheus configuration
prometheus:
  enabled: true
  server:
    nodeSelector:
      node-role: infra
    tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"
    persistentVolume:
      enabled: true
      size: 2Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
    service:
      type: NodePort
      nodePort: 30090

# kube-state-metrics configuration
kube-state-metrics:
  enabled: true
  nodeSelector:
    node-role: infra
  tolerations:
  - key: "node-role"
    operator: "Equal"
    value: "infra"
    effect: "NoSchedule"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Node Exporter configuration
prometheus-node-exporter:
  enabled: true
  # 部署到所有節點
  daemonset:
    enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
