---
- name: Configure Kind cluster nodes
  hosts: localhost
  connection: local
  become: no
  tasks:
    - name: Wait for cluster to be ready
      shell: kubectl get nodes
      register: nodes_status
      until: nodes_status.rc == 0
      retries: 30
      delay: 10

    - name: Get cluster nodes
      shell: kubectl get nodes -o name
      register: cluster_nodes

    - name: Run node configuration script
      shell: |
        chmod +x scripts/configure-nodes.sh
        scripts/configure-nodes.sh

    - name: Verify node configuration
      shell: kubectl get nodes --show-labels
      register: node_labels

    - name: Display node configuration
      debug:
        msg: |
          Node configuration completed:
          {{ node_labels.stdout }}
