---
- name: Join worker nodes to cluster
  hosts: workers
  become: yes
  tasks:
    - name: Wait for control plane to be ready
      wait_for:
        host: "{{ hostvars[groups['control_plane'][0]]['ansible_host'] }}"
        port: 6443
        timeout: 300

    - name: Get join command from control plane
      slurp:
        src: /tmp/join-command.sh
      delegate_to: "{{ groups['control_plane'][0] }}"
      register: join_command_file

    - name: Decode join command
      set_fact:
        join_command: "{{ join_command_file.content | b64decode }}"

    - name: Join worker node to cluster
      shell: "{{ join_command }}"
      register: join_result
      ignore_errors: yes

    - name: Wait for node to be ready
      wait_for:
        timeout: 120
      when: join_result.rc == 0

    - name: Display join result
      debug:
        msg: "{{ join_result.stdout }}"
      when: join_result.rc == 0
