---
- name: Configure node labels and taints
  hosts: kubernetes
  become: yes
  tasks:
    - name: Wait for cluster to be ready
      wait_for:
        timeout: 300
      delegate_to: "{{ groups['control_plane'][0] }}"
      when: inventory_hostname in groups['control_plane']

    - name: Get node name
      shell: hostname
      register: node_name

    - name: Apply node labels
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: "{{ node_name.stdout }}"
            labels:
              "{{ item }}": ""
        delegate_to: "{{ groups['control_plane'][0] }}"
      loop: "{{ node_labels[node_role] }}"
      when: node_role is defined

    - name: Apply node taints
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: "{{ node_name.stdout }}"
          spec:
            taints:
              - key: "{{ item.split(':')[0] }}"
                value: "{{ item.split(':')[1] if ':' in item else '' }}"
                effect: "{{ item.split(':')[2] if item.count(':') >= 2 else 'NoSchedule' }}"
        delegate_to: "{{ groups['control_plane'][0] }}"
      loop: "{{ node_taints[node_role] }}"
      when: node_role is defined

    - name: Display node configuration
      debug:
        msg: "Node {{ node_name.stdout }} configured with role {{ node_role }}"
      when: node_role is defined
