---
- name: Deploy ArgoCD
  hosts: localhost
  connection: local
  become: no
  tasks:
    - name: Add ArgoCD Helm repository
      shell: helm repo add argo https://argoproj.github.io/argo-helm
      ignore_errors: yes

    - name: Update Helm repositories
      shell: helm repo update

    - name: Create ArgoCD namespace
      shell: kubectl create namespace {{ argocd_namespace }}

    - name: Deploy ArgoCD using local Helm chart
      shell: |
        helm install argocd ../infrastructure/helm/argocd -n {{ argocd_namespace }}

    - name: Wait for ArgoCD to be ready
      shell: kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=argocd-server -n {{ argocd_namespace }} --timeout=300s

    - name: Start ArgoCD port-forward
      shell: |
        kubectl port-forward -n {{ argocd_namespace }} svc/argocd-server 8080:80 &
        echo "ArgoCD port-forward started on port 8080"

    - name: Get ArgoCD admin password
      shell: |
        kubectl -n {{ argocd_namespace }} get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
      register: argocd_password

    - name: Display ArgoCD access information
      debug:
        msg: |
          ArgoCD deployed successfully!
          URL: https://localhost:8080
          Username: admin
          Password: {{ argocd_password.stdout }}
