# ArgoCD Configuration
# ArgoCD 配置

# Global settings
global:
  namespace: argocd
  # 全域的 nodeSelector 和 tolerations
  nodeSelector:
    node-role: application
  tolerations:
  - key: "node-role"
    operator: "Equal"
    value: "application"
    effect: "NoSchedule"

# ArgoCD server configuration
server:
  service:
    type: NodePort
    nodePort: 30080
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

# ArgoCD controller configuration
controller:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# ArgoCD repo server configuration
repoServer:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Redis configuration
redis:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
