apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-service
  namespace: default
  labels:
    app: nginx-demo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: nginx-demo
